=== Helen-Parakhnevich/greenhouse/src/test/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">

    <element name="flower" type="tns:Flower" abstract="true"> </element>
    <element name="annual" type="tns:Annual" substitutionGroup="tns:flower"> </element>
    <element name="perennial" type="tns:Perennial" substitutionGroup="tns:flower"> </element>

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:annual" > </element>
                <element ref="tns:perennial"> </element>
            </sequence>
         </complexType>
    </element>

    <complexType name="Flower" >
        <sequence>
            <element name="soil" type="tns:Soil" > </element>
            <element name="visual" type="tns:VisualParameters" > </element>
            <element name="growing" type="tns:GrowingTips" > </element>
            <element type="string" name="plantingTime" > </element>
        </sequence>
        <attribute name="id" type="ID" use="required" />
        <attribute name="name" type="string" use="required"/>

    </complexType>

    <complexType name="Annual">
        <complexContent>
             <extension base="tns:Flower">
                 <all>
                     <element type="string" name="plantingTime" minOccurs="1" maxOccurs="1"> </element>
                 </all>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Perennial">
        <complexContent>
          <extension base="tns:Flower">
              <all>
                 <element name="evergreen" type="boolean" minOccurs="1" maxOccurs="1"></element>
                 <element name="rootType" type="tns:RootSystemType" minOccurs="1" maxOccurs="1"></element>
             </all>
         </extension>
        </complexContent>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="land_based"/>
        </restriction>
    </simpleType>

    <simpleType name="RootSystemType">
        <restriction base="string">
            <enumeration value="fibrous"/>
            <enumeration value="bulb"/>
            <enumeration value="tubers"/>
        </restriction>
    </simpleType>

    <complexType name="VisualParameters">
        <sequence>
            <element type="tns:Color" name="colorFlower"/>
            <element type="tns:Color" name="colorLeaves"/>
            <element type="int" name="averageSize"/>
        </sequence>
    </complexType>

    <complexType name="GrowingTips">
        <sequence>
            <element type="string" name="temperature"/>
            <element type="string" name="lighting"/>
            <element type="string" name="watering"/>
        </sequence>
    </complexType>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="white" />
            <enumeration value="green" />
            <enumeration value="blue" />
            <enumeration value="yellow" />
            <enumeration value="red" />
            <enumeration value="violet" />
            <enumeration value="orange" />
            <enumeration value="pink" />
        </restriction>
    </simpleType>

</schema>

=== Helen-Parakhnevich/greenhouse/src/test/resources/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd"
         xmlns="http://www.example.com/flowers">
    <annual id="abaa2a-faa8-4f55-bf51-d812411e571f" name="aster">
        <soil>podzolic</soil>
        <visual>
            <colorFlower>red</colorFlower>
            <colorLeaves>green</colorLeaves>
            <averageSize>40</averageSize>
        </visual>
        <growing>
            <temperature>10-30C</temperature>
            <lighting>800FC</lighting>
            <watering>medium</watering>
        </growing>
        <plantingTime>april</plantingTime>
    </annual>
    <perennial id="fb774a46-3c49-4174-b562-3dbd36671cc3" name="peony">
        <soil>land_based</soil>
        <visual>
            <colorFlower>pink</colorFlower>
            <colorLeaves>green</colorLeaves>
            <averageSize>100</averageSize>
        </visual>
        <growing>
            <temperature>0-35C</temperature>
            <lighting>600FC</lighting>
            <watering>medium</watering>
        </growing>
        <evergreen>false</evergreen>
        <rootType>fibrous</rootType>
    </perennial>
</flowers>

=== Helen-Parakhnevich/greenhouse/src/test/resources/flowers_invld.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.example.com/flowers flowers.xsd"
        xmlns="http://www.example.com/flowers">
    <annual id="40abaa2a-faa8-4f55-bf51-d812411e571f" name="aster">
        <so>podzolic</so>
        <vi>
            <colorFlower>red</colorFlower>
            <colorLeaves>green</colorLeaves>
            <averageSize>40</averageSize>
        </vi>
        <growing>
            <temperature> </temperature>
            <lighting>800FC</lighting>
            <watering>medium</watering>
        </growing>
        <plantingTime>APRIL</plantingTime>
    </annual>
    <perennial id="fb774a46-3c49-4174-b562-3dbd36671cc3" name="peony">
        <soil>land_based</soil>
        <visual>
            <colorFlower>red</colorFlower>
            <colorLeaves>green</colorLeaves>
            <averageSize>40</averageSize>
        </visual>
        <growing>
            <temperature> </temperature>
            <lighting>800FC</lighting>
            <watering>medium</watering>
        </growing>
        <evergreen>false</evergreen>
        <rootType>fibrous</rootType>
    </perennial>
</flowers>
